---
# tasks file for openstack_pools

- name: Connect to Ceph cluster
  include_tasks: connect.yml

- name: Create openstack pools
  shell: "{{ ceph_prompt }} ceph osd pool create {{ item }} 16"
  loop:
    - vms
    - volumes
    - images

- name: Create opensatck cephx key
  shell: "{{ ceph_prompt }} ceph auth add client.openstack mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=vms, allow rwx pool=volumes, allow rwx pool=images'"

- name: Get openstack cephx key
  shell: "{{ ceph_prompt }} ceph auth get client.openstack"
  register: ceph_auth_get

- name: Write openstack cephx key to file
  copy:
    dest: "{{ cephx_output }}"
    content: "{{ ceph_auth_get.stdout }}"

- name: Generate minimal ceph config
  shell: "{{ ceph_prompt }} ceph config generate-minimal-conf"
  register: ceph_config_get

- name: Write ceph.conf file
  copy:
    dest: "{{ ceph_conf_output }}"
    content: "{{ ceph_config_get.stdout }}"

- name: Write client/keyring into ceph.conf file
  lineinfile:
    path: "{{ ceph_conf_output }}"
    line: "[client]\nkeyring = ceph.client.openstack.keyring"
    state: present
