---
- name: look for required files in artifacts
  find:
    paths: "{{ artifacts }}"
    patterns:
      - crc-linux-amd64.tar.xz
      - pull-secret
  register: find_artifacts

- name: show artifacts
  fail:
    msg: "Download pull-secret & crc-linux-amd64.tar.xz from {{ url }} and save them in in {{ artifacts }}"
  when: find_artifacts.matched != 2

- name: Ensure we have necessary RPMs
  dnf:
    name: NetworkManager # python-kubernetes
    state: latest
  become: true

- name: Ensure we have necessary pip modules
  pip:
    name: openshift

- name: Ensure bin directory exists
  file:
    path: "{{ bin }}"
    state: directory

- name: Install odo in bin directory
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-linux-amd64
    dest: "{{ bin }}/odo"
    mode: '0700'
