---
# tasks file for ocs
- name: Ensure we have prerequisites
  include_tasks: pre.yml
  tags: always

- name: Authenticate for this session
  shell: "{{ oc }} login -u kubeadmin -p {{ kubeadmin_password }} {{ api }}"
  tags: always

- name: Ensure we have disks attached to use as OSDs
  include_tasks: disks.yml
  tags: disks

- name: Label node
  include_tasks: node.yml
  tags: node

- name: Deploy OCS resources
  include_tasks: ocs.yml
  tags: ocs

- name: Deploy Ceph toolbox
  include_tasks: toolbox.yml
  tags: toolbox

- name: check ceph health
  shell: "{{ oc }} rsh -n openshift-storage {{ toolbox }} ceph -s"
  register: ceph_status
  tags: toolbox

- name: show ceph status
  debug:
    msg: "{{ ceph_status.stdout_lines }}"
  tags: toolbox
