---
- name: Get node
  k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    api_version: v1
    kind: Node
  register: get_node

- name: Set facts about node
  set_fact:
    node_name: "{{ get_node.resources[0].metadata.name }}"
    node_labels: "{{ get_node.resources[0].metadata.labels }}"

- name: Label node to be able to deploy OCS pods
  shell: "{{ oc }} label nodes {{ node_name }} {{ item.key }}={{ item.value }}"
  when: item.key not in node_labels.keys()
  loop:
    - { key: "cluster.ocs.openshift.io/openshift-storage", value: "''"}
    - { key: "topology.rook.io/rack", value: "rack0" }
